# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('addr', models.CharField(max_length=128, verbose_name='地址')),
                ('port', models.IntegerField(verbose_name='SSH端口')),
                ('username', models.CharField(default='root', max_length=32, verbose_name='主机用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
